version: "3.8"
services:
  server:
    image: "infracloudio/csvserver"
    ports:
      - "9393:9300"
    environment:
      CSVSERVER_BORDER: Orange
    volumes:
      - /root/Infracloud/inputFile:/csvserver/inputdata
  prometheus:
    image: "prom/prometheus:v2.22.0"
    ports:
      - "9090:9090"
    volumes:
      - /root/Infracloud/prometheus.yml:/etc/prometheus/prometheus.yml
